name: Bug Report
description: File a bug report
title: "Bug: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        **Thanks for taking the time to fill out this bug report!**

  - type: textarea
    id: summary
    attributes:
      label: What happened?
      description: What bugs have you experienced?
      placeholder: Please describe how is the actual behaviour currently.
    validations:
      required: true
        
  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
    validations:
      required: false
        
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: Text
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: What do you expect?
      description: What is the expected behaviour?
      placeholder: Please describe how is the expected behaviour.
    validations:
      required: true
      
  - type: dropdown
    id: koishi-os
    attributes:
      label: What operating systems are you seeing the problem on?
      multiple: true
      options:
        - Windows
        - Windows Servers
        - Linux (Debian / Ubuntu, etc)
        - Linux (RatHat / Fedora / CentOS, etc)
        - Linux (Arch Linux / Manjaro, etc)
        - Linux (Others)
        - Mac
        - Other

  - type: dropdown
    id: koishi-platform
    attributes:
      label: What platforms are you seeing the problem on?
      multiple: true
      options:
        - OneBot
        - Discord
        - Telegram
        - Kook (Kaiheila)
        - Other
        
  - type: textarea
    id: others
    attributes:
      label: Anything else?
      description: |
        Related configs? Links? References?
        Anything that will give us more context about the issue you are encountering!
    validations:
      required: false
        
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow Contributor Covenant's [Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
