name: Bug Report
description: File a bug report
title: "Bug: "
labels: ["bug"]
assignees:
body:
  - type: markdown
    attributes:
      placeholder: |
        Please fill up this section.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: koishi-platform
    attributes:
      label: What platform are you seeing the problem on?
      multiple: true
      options:
        - None
        - OneBot
        - Discord
        - Telegram
        - Kook (Kaiheila)
        - Other
        - All
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow Contributor Covenant's [Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
